P98960-upper-lower-letter: P98960-upper-lower-letter.o
	g++ P98960-upper-lower-letter.o -o P98960-upper-lower-letter
P98960-upper-lower-letter.o: P98960-upper-lower-letter.cc
	g++ -c P98960-upper-lower-letter.cc
clean: 
	rm *.o P98960-upper-lower-letter

