P59539-harmonic-numbers: P59539-harmonic-numbers.o
	g++ P59539-harmonic-numbers.o -o P59539-harmonic-numbers
P59539-harmonic-numbers.o: P59539-harmonic-numbers.cc
	g++ -c P59539-harmonic-numbers.cc
clean: 
	rm *.o P59539-harmonic-numbers
