P29448-correct-dates: P29448-correct-dates.o
	g++ P29448-correct-dates.o -o P29448-correct-dates
P29448-correct-dates.o: P29448-correct-dates.cc
	g++ -c P29448-correct-dates.cc
clean:
	rm *.o P29448-correct-dates
