P97156-numbers-interval: P97156-numbers-interval.o
	g++ P97156-numbers-interval.o -o P97156-numbers-interval
P97156-numbers-interval.o: P97156-numbers-interval.cc
	g++ -c P97156-numbers-interval.cc
clean: 
	rm *.o P97156-numbers-interval
