P15613-temperatures: P15613-temperatures.o
	g++ P15613-temperatures.o -o P15613-temperatures
P15613-temperatures.o: P15613-temperatures.cc
	g++ -c P15613-temperatures.cc
clean:
	rm *.o P15613-temperatures

