P90615-max-of-three: P90615-max-of-three.o
	g++ P90615-max-of-three.o -o P90615-max-of-three
P90615-max-of-three.o: P90615-max-of-three.cc
	g++ -c P90615-max-of-three.cc
clean: 
	rm *.o P90615-max-of-three

